/**
 * Mock 数据生成器
 * 用于本地测试，不依赖真实接口
 * 
 * 数据结构仿照早期抓包（trace.har，该文件已不在仓库）的返回形状，仅供无后端时调界面
 */

const MOCK_DATA = {
  // 组件 E00301 的服务列表
  'E00301': [
    {
      serverCoding: 'PsnGlobalRemittanceAccountsQuery',
      serviceName: '全球汇划账户列表查询',
      interfaceCode: 'PsnGlobalRemittanceAccountsQuery',
      provideSystemNumber: 'E00301',
      assemblyNo: 'E00301',
      sheetProductBatch: '2611批次',
      prodBatch: '2611批次',
      offerServerState: '功能测试基线',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '1',
      principal: '',
      principalName: null,
      implementationUnit: '',
      deptId: '1465A',
      deptName: '中国银行软件中心（西安）开发一部',
      provideComponentName: '互联网金融服务平台',
      assemblyName: '互联网金融服务平台',
      sysServeNo: 'E00301TP0460',
      sysServeEnName: 'PsnGlobalRemittanceAccountsQuery',
    },
    {
      serverCoding: 'CustInfoQueryService',
      serviceName: '客户信息查询服务',
      interfaceCode: 'CustInfoQueryService',
      provideSystemNumber: 'E00301',
      assemblyNo: 'E00301',
      sheetProductBatch: '2611批次',
      prodBatch: '2611批次',
      offerServerState: '正式版基线',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '1',
      principal: '张三',
      principalName: '张三',
      implementationUnit: '数据中心',
      deptId: '1465A',
      deptName: '中国银行软件中心（西安）开发一部',
      provideComponentName: '互联网金融服务平台',
      assemblyName: '互联网金融服务平台',
      sysServeNo: 'E00301TP0461',
      sysServeEnName: 'CustInfoQueryService',
    },
    {
      serverCoding: 'TransInfoQueryService',
      serviceName: '交易流水查询服务',
      interfaceCode: 'TransInfoQueryService',
      provideSystemNumber: 'E00301',
      assemblyNo: 'E00301',
      sheetProductBatch: '2610批次',
      prodBatch: '2610批次',
      offerServerState: '开发基线',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '0',
      principal: '李四',
      principalName: '李四',
      implementationUnit: '研发中心',
      deptId: '1465A',
      deptName: '中国银行软件中心（西安）开发二部',
      provideComponentName: '互联网金融服务平台',
      assemblyName: '互联网金融服务平台',
      sysServeNo: 'E00301TP0462',
      sysServeEnName: 'TransInfoQueryService',
    },
    {
      serverCoding: 'ShortMsgNotifyService',
      serviceName: '短信通知服务',
      interfaceCode: 'ShortMsgNotifyService',
      provideSystemNumber: 'E00301',
      assemblyNo: 'E00301',
      sheetProductBatch: '2609批次',
      prodBatch: '2609批次',
      offerServerState: '正式版基线',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '1',
      principal: '王五',
      principalName: '王五',
      implementationUnit: '渠道部',
      deptId: '1465B',
      deptName: '中国银行软件中心（西安）开发三部',
      provideComponentName: '互联网金融服务平台',
      assemblyName: '互联网金融服务平台',
      sysServeNo: 'E00301TP0463',
      sysServeEnName: 'ShortMsgNotifyService',
    },
    {
      serverCoding: 'LimitControlService',
      serviceName: '额度控制服务',
      interfaceCode: 'LimitControlService',
      provideSystemNumber: 'E00301',
      assemblyNo: 'E00301',
      sheetProductBatch: '2608批次',
      prodBatch: '2608批次',
      offerServerState: '编辑中',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '0',
      principal: '赵六',
      principalName: '赵六',
      implementationUnit: '研发中心',
      deptId: '1465A',
      deptName: '中国银行软件中心（西安）开发一部',
      provideComponentName: '互联网金融服务平台',
      assemblyName: '互联网金融服务平台',
      sysServeNo: 'E00301TP0464',
      sysServeEnName: 'LimitControlService',
    },
  ],

  // 组件 E00302 的服务列表
  'E00302': [
    {
      serverCoding: 'FxRateQueryService',
      serviceName: '外汇汇率查询服务',
      interfaceCode: 'FxRateQueryService',
      provideSystemNumber: 'E00302',
      assemblyNo: 'E00302',
      sheetProductBatch: '2611批次',
      prodBatch: '2611批次',
      offerServerState: '正式版基线',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '1',
      principal: '周八',
      principalName: '周八',
      implementationUnit: '国际业务部',
      deptId: '1466A',
      deptName: '中国银行国际业务部',
      provideComponentName: '国际业务服务平台',
      assemblyName: '国际业务服务平台',
      sysServeNo: 'E00302TP0101',
      sysServeEnName: 'FxRateQueryService',
    },
    {
      serverCoding: 'CrossBorderPayService',
      serviceName: '跨境支付服务',
      interfaceCode: 'CrossBorderPayService',
      provideSystemNumber: 'E00302',
      assemblyNo: 'E00302',
      sheetProductBatch: '2610批次',
      prodBatch: '2610批次',
      offerServerState: '功能测试基线',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '0',
      principal: '吴九',
      principalName: '吴九',
      implementationUnit: '清算中心',
      deptId: '1466A',
      deptName: '中国银行清算中心',
      provideComponentName: '国际业务服务平台',
      assemblyName: '国际业务服务平台',
      sysServeNo: 'E00302TP0102',
      sysServeEnName: 'CrossBorderPayService',
    },
    {
      serverCoding: 'TradeFinanceService',
      serviceName: '贸易融资服务',
      interfaceCode: 'TradeFinanceService',
      provideSystemNumber: 'E00302',
      assemblyNo: 'E00302',
      sheetProductBatch: '2609批次',
      prodBatch: '2609批次',
      offerServerState: '开发基线',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '1',
      principal: '郑十',
      principalName: '郑十',
      implementationUnit: '公司业务部',
      deptId: '1466B',
      deptName: '中国银行公司业务部',
      provideComponentName: '国际业务服务平台',
      assemblyName: '国际业务服务平台',
      sysServeNo: 'E00302TP0103',
      sysServeEnName: 'TradeFinanceService',
    },
  ],

  // 组件 E00303 的服务列表
  'E00303': [
    {
      serverCoding: 'CreditCardApplyService',
      serviceName: '信用卡申请服务',
      interfaceCode: 'CreditCardApplyService',
      provideSystemNumber: 'E00303',
      assemblyNo: 'E00303',
      sheetProductBatch: '2611批次',
      prodBatch: '2611批次',
      offerServerState: '正式版基线',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '1',
      principal: '冯十一',
      principalName: '冯十一',
      implementationUnit: '信用卡中心',
      deptId: '1467A',
      deptName: '中国银行信用卡中心',
      provideComponentName: '信用卡服务平台',
      assemblyName: '信用卡服务平台',
      sysServeNo: 'E00303TP0201',
      sysServeEnName: 'CreditCardApplyService',
    },
    {
      serverCoding: 'BillQueryService',
      serviceName: '账单查询服务',
      interfaceCode: 'BillQueryService',
      provideSystemNumber: 'E00303',
      assemblyNo: 'E00303',
      sheetProductBatch: '2610批次',
      prodBatch: '2610批次',
      offerServerState: '正式版基线',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '1',
      principal: '陈十二',
      principalName: '陈十二',
      implementationUnit: '信用卡中心',
      deptId: '1467A',
      deptName: '中国银行信用卡中心',
      provideComponentName: '信用卡服务平台',
      assemblyName: '信用卡服务平台',
      sysServeNo: 'E00303TP0202',
      sysServeEnName: 'BillQueryService',
    },
    {
      serverCoding: 'InstallmentPayService',
      serviceName: '分期付款服务',
      interfaceCode: 'InstallmentPayService',
      provideSystemNumber: 'E00303',
      assemblyNo: 'E00303',
      sheetProductBatch: '2609批次',
      prodBatch: '2609批次',
      offerServerState: '功能测试基线',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '0',
      principal: '褚十三',
      principalName: '褚十三',
      implementationUnit: '信用卡中心',
      deptId: '1467B',
      deptName: '中国银行信用卡中心产品部',
      provideComponentName: '信用卡服务平台',
      assemblyName: '信用卡服务平台',
      sysServeNo: 'E00303TP0203',
      sysServeEnName: 'InstallmentPayService',
    },
    {
      serverCoding: 'PointsRedeemService',
      serviceName: '积分兑换服务',
      interfaceCode: 'PointsRedeemService',
      provideSystemNumber: 'E00303',
      assemblyNo: 'E00303',
      sheetProductBatch: '2608批次',
      prodBatch: '2608批次',
      offerServerState: '正式版基线',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '1',
      principal: '卫十四',
      principalName: '卫十四',
      implementationUnit: '信用卡中心',
      deptId: '1467A',
      deptName: '中国银行信用卡中心会员部',
      provideComponentName: '信用卡服务平台',
      assemblyName: '信用卡服务平台',
      sysServeNo: 'E00303TP0204',
      sysServeEnName: 'PointsRedeemService',
    },
    {
      serverCoding: 'FeeWaiveService',
      serviceName: '年费减免服务',
      interfaceCode: 'FeeWaiveService',
      provideSystemNumber: 'E00303',
      assemblyNo: 'E00303',
      sheetProductBatch: '2607批次',
      prodBatch: '2607批次',
      offerServerState: '编辑中',
      serviceStatus: null,
      subscriberStatus: null,
      isChecked: '0',
      principal: '蒋十五',
      principalName: '蒋十五',
      implementationUnit: '信用卡中心',
      deptId: '1467A',
      deptName: '中国银行信用卡中心运营部',
      provideComponentName: '信用卡服务平台',
      assemblyName: '信用卡服务平台',
      sysServeNo: 'E00303TP0205',
      sysServeEnName: 'FeeWaiveService',
    },
  ],
};

// 默认订阅的服务编码（模拟用户已订阅的）
// 使用真实接口返回的 serverCoding 格式
const DEFAULT_SUBSCRIBED = [
  'PsnGlobalRemittanceAccountsQuery',
  'CustInfoQueryService',
  'FxRateQueryService',
  'CreditCardApplyService',
  'BillQueryService',
];

// 暴露给全局（支持浏览器和 Node.js）
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { MOCK_DATA, DEFAULT_SUBSCRIBED };
}

if (typeof window !== 'undefined') {
  window.MOCK_DATA = MOCK_DATA;
  window.DEFAULT_SUBSCRIBED = DEFAULT_SUBSCRIBED;
}
